// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cldmhftuxbkibnxiumup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZG1oZnR1eGJraWJueGl1bXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjA4NDUsImV4cCI6MjA2ODM5Njg0NX0.ujQ0zibq49X1XHkAZSREBKNcWFFAjKMEtXWUEW-feb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});